import turtle
t = turtle.Turtle()
colors=['red', 'purple', 'blue', 'green', 'yellow', 'orange', 'pink','light blue']
turtle.bgcolor("black")
t.pensize(5)z
for x in range(740):
    t.pencolor(colors[x%6])
    t.width(x/100+1)
    t.forward(x)
    t.left(59)
for i in range(1):
    t.penup()
    t.color(colors[i%8])
    t.goto(-200,-40)
    t.pendown()
    t.right(100)
    t.shape("turtle")
    t.color("light green")
    t.left(70)
    t.forward(100)
    t.left(-140)
    t.forward(100)
    t.left(180)
    t.forward(50)
    t.left(70)
    t.forward(35)
    
    t.left(180)
    t.forward(35)
    t.right(70)
    t.forward(50)
    t.penup()
    t.left(70)
    t.forward(20)
    t.pendown()
    t.left(90)
    t.forward(90)
    t.right(155)
    t.forward(100)
    t.left(155)
    t.forward(90)
    t.left(180)
    t.penup()
    t.forward(90)
    t.left(90)
    
    t.forward(30)
    t.left(90)
    t.pendown()
    t.forward(90)
    t.right(90)
    for i in range(150):
        t.right(1.2)
        t.forward(0.95)
        
    t.penup()
    t.left(180)
    t.forward(60)
    t.left(90)
    t.pendown()
    
    t.forward(90)
    t.right(90)
    for i in range(90):
        t.right(2)
        t.forward(1)
    t.left(135)
    t.forward(45)
    t.left(45)
    t.penup()
    t.forward(15)
    t.left(90)
    t.pendown()
    t.forward(90)
    t.right(90)
    t.forward(30)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(35)
    t.left(180)
    t.forward(35)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(40)
    t.penup()
    t.forward(20)
    t.pendown()
    for i in range(80):
        t.left(2)
        t.forward(0.8)
    for i in range(80):
        t.right(2)
        t.forward(0.8)
    t.forward(200)
    